# Generated by Django 4.0.5 on 2022-07-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_type_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uniform_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
    ]
